name: PMD JavaScript Code Scan

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '20 3 * * 5' # Run on Fridays at 03:20

permissions:
  contents: read

jobs:
  pmd-js-code-scan:
    permissions:
      contents: read # To fetch code with actions/checkout
      security-events: write # For uploading SARIF results
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11 (PMD requires a Java runtime)
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Run PMD for JavaScript
        id: pmd
        uses: pmd/pmd-github-action@v1
        with:
          rulesets: |
            category/javascript/bestpractices.xml,
            category/javascript/codestyle.xml,
            category/javascript/errorprone.xml,
            category/javascript/performance.xml
          sourcePath: 'src/' # Update with the actual path to your JavaScript code
          analyzeModifiedFilesOnly: false
          createGitHubAnnotations: true

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: pmd-report.sarif
