name: Code Quality Check

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  pmd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Run PMD for JavaScript
        id: pmd
        uses: pmd/pmd-github-action@v1
        with:
          rulesets: |
            https://raw.githubusercontent.com/pmd/pmd/main/pmd-javascript/src/main/resources/category/ecmascript/bestpractices.xml,
            https://raw.githubusercontent.com/pmd/pmd/main/pmd-javascript/src/main/resources/category/ecmascript/codestyle.xml,
            https://raw.githubusercontent.com/pmd/pmd/main/pmd-javascript/src/main/resources/category/ecmascript/errorprone.xml,
            https://raw.githubusercontent.com/pmd/pmd/main/pmd-javascript/src/main/resources/category/ecmascript/performance.xml,
            https://raw.githubusercontent.com/pmd/pmd/main/pmd-javascript/src/main/resources/category/ecmascript/design.xml,
            https://raw.githubusercontent.com/pmd/pmd/main/pmd-javascript/src/main/resources/category/ecmascript/security.xml
          sourcePath: 'src/'
          analyzeModifiedFilesOnly: false
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          createGitHubAnnotations: true
        env:
          JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/11.0.24-8/x64
          JAVA_HOME_11_X64: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/11.0.24-8/x64

      - name: Upload PMD Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: pmd-report
          path: pmd-report.sarif
